# Generated by Django 4.1.7 on 2023-03-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_test_number_userresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('number', 'set_of_tests')},
        ),
    ]
