# Generated by Django 4.1.7 on 2023-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_test_number_alter_test_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresults',
            name='count_correct_answer',
            field=models.IntegerField(default=0),
        ),
    ]
