# Generated by Django 4.1.7 on 2023-03-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_userresults_count_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresults',
            name='set_of_tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='questionnaire.setoftests'),
        ),
    ]
