# Generated by Django 4.1.7 on 2023-04-24 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_userresults_set_of_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='set_of_tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='questionnaire.setoftests', verbose_name='Набор тестов'),
        ),
    ]
